contact:
    path:     /{_locale}
    defaults: { _controller: AppBundle:Default:index, _locale: en }
    requirements:
        _locale: en|fr|uk

information:
    path:     /{_locale}/information
    defaults: { _controller: AppBundle:Default:information, _locale: en }
    requirements:
        _locale: en|fr|uk
#app:
 #   resource: "@AppBundle/Controller/"
  #  type:     annotation
