security:
    encoders:
        AppBundle\Entity\User\User: #plaintext
              algorithm: sha256
    providers:
        our_db_provider:
            entity:
                class: AppBundle\Entity\User\User
                property: login

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_USER }