security:
    encoders:
        AppBundle\Entity\User\User: #plaintext
              algorithm: sha256
    providers:
        our_db_provider:
            entity:
                class: AppBundle\Entity\User\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            anonymous: ~

        default:
            anonymous: true
            security: true
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_USER }