security:
    providers:
        our_db_provider:
            entity:
                class: AppBundle\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: true
            security: true
            form_login:
                login_path: login
                check_path: login
                default_target_path: homepage
            logout:
                path:   /logout
                target: /login


    encoders:
            Symfony\Component\Security\Core\User\User: bcrypt
            AppBundle\Entity\User: bcrypt

    access_control:
        # require ROLE_ADMIN for /admin*
         - { path: ^/vocabulary, roles: ROLE_USER }