# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    providers:
            chain_provider:
                 chain:
                      providers: [main, in_memory]
            main:
                entity:
                    class: AppBundle:User
            in_memory:
                memory:
                    users:
                        admin:
                            password: $2y$13$Opei3SZDFbiftGnPr8XrQOvP2/bLv..FGMNJh5sAqWwZvY0gzSUQ6
                            roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            form_login:
                    login_path: login
                    check_path: login
            logout:
                  path:   /logout
                  target: /


    encoders:
            Symfony\Component\Security\Core\User\User: bcrypt
            AppBundle\Entity\User: bcrypt

