
parameters:

services:

       app.doctrine_listener:
               class: AppBundle\Services\DoctrineListener
               arguments: ['@security.password_encoder']
               tags:
                    - { name: doctrine.event_subscriber }

       app.locale_listener:
               class: AppBundle\EventListener\LocaleListener
               arguments: ['%kernel.default_locale%']
               tags:
                   - { name: kernel.event_subscriber }

       app.user_locale_listener:
               class: AppBundle\EventListener\UserLocaleListener
               arguments: ['@session']
               tags:
                   - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
