# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.form.manager:
        class: AppBundle\Services\FormManager
        arguments: ["@security.password_encoder", "@form.factory", "@doctrine"]
  app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true
  app.user_locale_listener:
          class: AppBundle\EventListener\UserLocaleListener
          arguments: ['@session']
          tags:
              - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
  app.locale_listener:
          class: AppBundle\EventListener\LocaleListener
          arguments: ['%kernel.default_locale%']
          tags:
              - { name: kernel.event_subscriber }
