<?php

namespace AppBundle\Repository\User;

use AppBundle\Entity\User\User;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public $name;
    public function findByNameUser($name){
        $qb = $this->createQueryBuilder('u');
        $qb->select('u')
           // ->from('User', 'u')
            ->where('u.username =:name')
            ->setParameter('name', $name);
             //->getQuery()
            //->getResult();
        return $qb->getQuery()->getResult();
    }
}
