<?php

namespace AppBundle\Repository\WordTranslation;

/**
 * WordTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
